---
driver_plugin: vagrant
driver_config:
  provider: virtualbox
  memory: 512

platforms:
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: true

suites:
- name: default
  run_list:
  - recipe[virtualbox]
  - recipe[vagrant]
  attributes:
    vagrant:
      url: http://files.vagrantup.com/packages/7e400d00a3c5a0fdf2809c8b5001a035415a607b/vagrant_1.2.2_x86_64.deb
      plugins:
      - vagrant-berkshelf
